inherit_from: .rubocop_todo.yml

require:
  - standard
  - rubocop-rails

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*

Rails:
  Enabled: true
Style/MixinUsage:
  Exclude:
    - bin/**/*
Bundler/DuplicatedGem:
  Enabled: false
